version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: my_mongo
    ports:
      - "27017:27017"
    networks:
      - go-net
  go_server:
    build: .
    container_name: go_contianer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - go-net
    depends_on:
      - "mongodb"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
networks:
  go-net: